config/routes.rb
Rails.application.routes.draw do

  root 'orders#home'

  resources :oysters
  resources :orders do
    member do
      post 'done'
      post 'remind'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  before_save :set_activation_code

  has_and_belongs_to_many :oysters
  has_many :orders_oysters

  validates_presence_of :phone
  validates_presence_of :name
  validates :phone, phone_number: { ten_digits: true }

  def set_activation_code
    self.activation_code = nil
    while self.activation_code == nil
      word = Wordlist::WORDS.sample
      if Order.where(activation_code: word).first
        break
      else
        self.activation_code = word
      end
    end
  end

  def formatted
    attributes.merge(oysters: formatted_oysters)
  end

  def formatted_oysters
    orders_oysters.map do |order_oyster|
      return if order_oyster.count.blank?
      oyster_name = Oyster.find(order_oyster.oyster_id).name
      [oyster_name, order_oyster.count]
    end
  end

  def twilio_client
    Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def send_initial_message
    return unless ENV.key? 'TWILIO_ACCOUNT_SID'
    begin
      twilio_client.messages.create(
        to: phone,
        from: ENV['TWILIO_PHONE_NUMBER'],
        body: "Hi #{name}! We'll let you know when your order is ready, or you can check the status with code: #{activation_code}. You owe $#{amount_owed}"
      )
    rescue Twilio::REST::RequestError => e
      self.errors.add(:oops, e.message)
    end
  end

  def send_ready_message
    twilio_client.messages.create(
      to: phone,
      from: ENV['TWILIO_PHONE_NUMBER'],
      body: "Hi #{name}! Your order is ready."
    )
  end

  def send_reminder_message
    twilio_client.messages.create(
      to: phone,
      from: ENV['TWILIO_PHONE_NUMBER'],
      body: "Hi #{name}! Your order is ready. Get it while it's cold."
    )
  end

  def amount_owed
    orders_oysters.pluck(:count).sum
  end

  def validate_order_oysters(order_oysters)
    total_count = 0
    order_oysters.each do |name, count|
      oyster = Oyster.where(name: name).first
      unless oyster
        self.errors.add(:oops!, "Oyster does not exist.")
        break
      end
      if count.to_i > oyster.max
        self.errors.add(:darn, "can't order more than #{oyster.max} #{oyster.name} oysters!")
      end
      if oyster.count - count.to_i < 0
        self.errors.add(:shoot, "only #{oyster.count} #{oyster.name} oysters left.")
      end
      total_count += count.to_i
    end
    self.errors.add(:golly, "only 12 oysters per order please.") if total_count > 12
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:orders].permit(:name, :phone))
    @order.status = 'Pending'
    @order.validate_order_oysters(params[:orders][:oysters])

    if @order.errors.blank?
      if @order.errors.blank? && @order.save
        params[:orders][:oysters].each do |name, count|
          oyster = Oyster.where(name: name).first
          OrdersOyster.create!(order: @order, oyster: oyster, count: count) if !count.blank?
          oyster.recalculate_count!(count)
        end
        @order.send_initial_message
        redirect_to order_path(activation_code: @order.activation_code.downcase, id: @order.id)
        return
      end
    end
    render 'new'
  end

  def show
    @order = Order.where(activation_code: params[:activation_code].downcase).first
    unless @order
      @error = 'Code is invalid.'
      render 'home'
    end
  end

  def index
    if params[:status] == 'Done'
      @status = 'Done'
      @orders = Order.where(status: 'Done').order(created_at: :desc).all
    else
      @status = 'Pending'
      @orders = Order.where(status: 'Pending').all
    end
  end

  def done
    @order = Order.find(params[:id])
    @order.update_attributes!(status: 'Done')
    @order.send_ready_message if ENV.key? 'TWILIO_ACCOUNT_SID'
    redirect_to orders_path(status: 'Pending') # can be smarter here
  end

  def remind
    @order = Order.find(params[:id])
    @order.send_reminder_message if ENV.key? 'TWILIO_ACCOUNT_SID'
    redirect_to orders_path(status: 'Done') # can be smarter here
  end
end

app/helpers/order_helper.rb
module OrderHelper
  MENU = {
    blue: 25,
    orange: 20
  }
end

app/views/orders/home.html.erb
<% unless @error.nil? %>
  <div class='error'>
    <%= @error %>
  </div>
<% end %>
<div class='inner'>
  <div class='orders-sub available-oysters'>
    <div class='text-label'>
      Available oysters
    </div>
    <div align='center' class='small-text-label'>
      <table>
      <% Oyster.all.each do |oyster| %>
      <tr>
        <td><%= "#{oyster.name}: " %></td>
        <td align='right'><%= oyster.count %></td>
      </tr>
      <% end %>
      </table>
    </div>
  </div>
  <div class='orders-options'>
    <div class='orders-sub'>
      <div class='orders-button'>
        <%= link_to 'New Order', new_order_path %>
      </div>
    </div>
    <div class='orders-sub activation-form'>
      <%= form_tag '/orders/show', method: :get do %>
        <div class='orders-sub'>
          <%= text_field_tag 'activation_code', nil, placeholder: 'Code' %>
        </div>
        <%= submit_tag 'See Status', id: 'activation_code_submit', class: 'orders-button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class='orders-index'>
  <div class='orders-index-categories center'>
    <span class="text-important <%= 'text-purple' if @status == 'Pending' %>">
      <%= link_to 'Pending', orders_path(status: 'Pending') %>
    </span>
    <span> | </span>
    <span class="text-important <%= 'text-purple' if @status == 'Done' %>">
      <%= link_to 'Completed', orders_path(status: 'Done') %>
    </span>
  </div>
  <div class='inner'>
    <% @orders.each do |order| %>
      <div class='orders-each-order'>
        <div class='orders-sub'>
          <div class='text-label'><%= order.name %></div>
          <span class='text-label'>Owes: </span>
          <span><%= "$#{order.amount_owed}" %></span>
        </div>
        <div class='orders-sub'>
          <div class='orders-show-oysters'>
            <% if order.formatted_oysters.present? %>
              <% order.formatted_oysters.each do |oyster| %>
                <div class='text-accent'>
                  <span class='text-purple'><%= "#{oyster[0]}: "%></span>
                  <span><%= oyster[1]%></span>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <% if order.status == 'Pending' %>
          <div class='orders-sub'>
            <div class='orders-button'>
              <%= link_to 'Mark Done', done_order_path(order), method: :post %>
            </div>
          </div>
        <% else %>
          <div class='orders-sub'>
            <div class='orders-button'>
              <%= link_to 'Remind', remind_order_path(order), method: :post %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class='new-order-form'>
  <% if @order.errors.any? %>
    <div class='error'>
      <% @order.errors.messages.each do |attr, message| %>
        <div><%= "#{attr.capitalize} #{message.first}" %></div>
      <% end %>
    </div>
  <% end %>
  <div class='inner'>
    <%= form_tag '/orders', method: :post do %>
      <div class='orders-sub text-label'>
        <%= label_tag "Your name" %>
        <%= text_field_tag 'orders[name]' %>
      </div>
      <div class='orders-sub text-label'>
        <%= label_tag "Phone number" %>
        <%= text_field_tag 'orders[phone]' %>
      </div>
      <% Oyster.all.each do |oyster| %>
        <div class='orders-sub text-label'>
          <%= label_tag oyster.name %>
          <%= number_field_tag "orders[oysters][#{oyster.name}]", 0, class: 'number-input' %>
        </div>
      <% end %>
      <div class='orders-sub'>
        <%= submit_tag 'Submit order', class: 'orders-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class='orders-sub'>
  <div class='text-label'>
    Status
  </div>
  <div class='text-accent text-purple'><%= @order.status %></div>
</div>

<div class='orders-sub'>
  <div class='text-label'>
    You owe
  </div>
  <div class='text-accent text-purple'><%= "$#{@order.amount_owed}" %></div>
</div>

<div class='orders-sub'>
  <div class='text-label'>
    Activation code
  </div>
  <div class='text-accent'><%= @order.activation_code %></div>
</div>

<div class='orders-sub'>
  <div class='text-label'>
    Name
  </div>
  <div class='text-accent'><%= @order.name %></div>
</div>

<div class='orders-sub'>
  <div class='text-label'>
    Phone Number
  </div>
  <div class='text-accent'><%= @order.phone %></div>
</div>

<div class='orders-sub'>
  <div class='text-label'>
    Order
  </div>
  <div class='orders-show-oysters'>
    <% @order.formatted_oysters.each do |oyster| %>
      <div class='text-accent'><%= "#{oyster[0]}: #{oyster[1]}" %></div>
    <% end %>
  </div>
</div>